version: '3.4'

services:
  ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

